/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/machine.glb --typescript 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/machine.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2, 0.137, 4.85]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0, 0.137, 5.05]} rotation={[Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_1.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2, -1.265, 2.384]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_2.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0, -1.265, 2.184]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_3.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0.05, -2.036, 2.382]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_4.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0.05, -2.036, 2.182]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_5.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[1.95, -2.036, 2.182]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_6.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[1.95, -2.036, 2.382]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_7.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.95, 0.091, 12.85]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <group position={[-0.8, 0, 0]} rotation={[0, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_35.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 0.9, 0]}>
          <mesh geometry={nodes.Solid1_36.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.8, 0.9, 0]} rotation={[0, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_37.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.85, -0.05, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_38.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 0.9, 0]} rotation={[-Math.PI, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_39.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.005, 0.85, 0.05]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_40.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_41.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.795, 0.85, 0.05]} rotation={[Math.PI / 2, 0, -Math.PI]}>
          <mesh geometry={nodes.Solid1_42.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 0, 1.105]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_43.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, 0.05, 1.105]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_44.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.05, 0.825, 2.241]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_45.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.05, -0.075, 2.241]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_46.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.85, 0.825, 2.241]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_47.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.75, 0.075, 2.241]} rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_48.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[0, 0.9, 1.104]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_49.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.825, 0.05, 1.104]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_50.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 0.915, 0.03]} rotation={[-Math.PI / 4, 0, 0]}>
          <mesh geometry={nodes.Solid1_51.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.8, 3.161, 2.276]} rotation={[2.356, 0, -Math.PI]}>
          <mesh geometry={nodes.Solid1_52.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 2.861, 2.006]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_53.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 2.641, 1.786]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_54.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 2.421, 1.566]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_55.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 2.201, 1.346]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_56.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 1.981, 1.126]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_57.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 1.761, 0.906]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_58.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 1.541, 0.686]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_59.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 1.321, 0.466]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_60.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, 1.101, 0.246]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_61.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.8, 2.986, 1.976]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_62.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 2.766, 1.756]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_63.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 2.546, 1.536]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_64.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 2.326, 1.316]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_65.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 2.106, 1.096]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_66.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 1.886, 0.876]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_67.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 1.416, 0.651]}>
          <mesh geometry={nodes.Solid1_68.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 1.446, 0.436]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_69.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.8, 1.226, 0.216]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_70.geometry} material={materials.Default} scale={0.01} />
        </group>
        <group position={[-0.825, 1.938, 1.104]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_71.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.03, 1.938, 1.105]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_72.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.825, -0.01, -0.005]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_73.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, -0.01, -0.005]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_74.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, 0.91, -0.005]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Solid1_75.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.045, -0.01, -0.985]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_76.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, 0.01, -0.985]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_77.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, 0.916, -0.991]} rotation={[-Math.PI / 4, 0, 0]}>
          <mesh geometry={nodes.Solid1_78.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, 2.809, 0.911]}>
          <mesh geometry={nodes.Solid1_79.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, 1.859, -0.039]}>
          <mesh geometry={nodes.Solid1_80.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.805, -0.01, -0.465]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_81.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.025, 0.89, -0.465]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_82.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[-0.85, 0.95, -0.005]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Solid1_83.geometry} material={materials.Default} scale={0.01} />
        </group>
        <mesh geometry={nodes.Solid1_34.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[4, 0.096, 12]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Solid1_8.geometry} material={materials.Default} scale={0.01} />
      </group>
      <group position={[4, 0.096, 8.835]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Solid1_9.geometry} material={materials.Default} scale={0.01} />
      </group>
      <group position={[3.975, 1.06, 10.62]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_10.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.975, 1.06, 9.327]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_11.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2.87, 1.06, 11.96]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_12.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2.87, 1.06, 10.874]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_13.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.975, 1.08, 10.617]}>
        <mesh geometry={nodes.Solid1_14.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.975, 1.08, 9.33]} rotation={[Math.PI, 0, 0]}>
        <mesh geometry={nodes.Solid1_15.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.975, 1.08, 9.33]}>
        <mesh geometry={nodes.Solid1_16.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2.87, 1.08, 10.854]} rotation={[0, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Solid1_17.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2.85, 1.08, 11.96]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_18.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2.85, 0.56, 11.96]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_19.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[4, 0.1, 5.028]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Solid1_20.geometry} material={materials.Default} scale={0.01} />
      </group>
      <group position={[3.975, 0.1, 6.52]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_21.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.975, 0.1, 5.078]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_22.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.14, 0.1, 5.077]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_23.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.975, 1.08, 5.098]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Solid1_24.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.975, 1.08, 6.52]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Solid1_25.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[3.995, 1.08, 5.078]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_26.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0, 0.549, 10.651]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_27.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[1.939, -2.093, 3.003]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_28.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[1.939, -2.093, 2.773]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_29.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[1.427, -2.036, 3.013]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_30.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[1.427, -2.036, 2.763]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_31.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0, 0.545, 10.651]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Solid1_32.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2, 0.545, 10.651]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.Solid1_33.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0.06, -0.057, 0]}>
        <group position={[1.88, -2.036, 0]}>
          <mesh geometry={nodes.Solid1_84.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.88, 0, 0]}>
          <mesh geometry={nodes.Solid1_85.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -2.036, 0]}>
          <mesh geometry={nodes.Solid1_87.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.88, -1.979, 0.057]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_88.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -1.979, 0.057]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_89.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.88, -1.979, 11.943]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_90.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -1.979, 11.943]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_91.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, 0, 0.06]} rotation={[Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_92.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, -2.036, 0.06]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_93.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, 0, 11.94]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_94.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, -2.036, 11.94]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_95.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -1.979, 4.021]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_96.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -1.979, 7.979]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_97.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.88, -1.979, 7.979]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_98.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.88, -1.979, 4.021]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_99.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, -2.036, 3.436]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_100.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, -2.036, 5.536]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_101.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, -2.036, 5.914]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_102.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, -2.036, 9.714]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_103.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.879, -2.036, 7.314]} rotation={[Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_104.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.877, -2.036, 11.114]} rotation={[Math.PI, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_105.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <mesh geometry={nodes.Solid1_86.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[0.05, 2.102, 0]}>
        <group position={[0, -2.054, 0]}>
          <mesh geometry={nodes.Solid1_107.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, 0, 0]}>
          <mesh geometry={nodes.Solid1_108.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -2.054, 0]}>
          <mesh geometry={nodes.Solid1_109.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -2.006, 11.952]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_110.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 0.048]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_111.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 0.048]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_112.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 11.952]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_113.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, 0, 0.05]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_114.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 0.05]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_115.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 11.95]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_116.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.895, 0, 11.95]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_117.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 7.985]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_118.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 4.015]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_119.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 4.015]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_120.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 7.985]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_121.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <mesh geometry={nodes.Solid1_106.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2.05, -0.048, 0]}>
        <group position={[0, -2.054, 0]}>
          <mesh geometry={nodes.Solid1_123.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, 0, 0]}>
          <mesh geometry={nodes.Solid1_124.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -2.054, 0]}>
          <mesh geometry={nodes.Solid1_125.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -2.006, 11.952]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_126.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 0.048]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_127.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 0.048]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_128.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 11.952]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_129.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, 0, 0.05]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_130.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 0.05]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_131.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 11.95]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_132.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.895, 0, 11.95]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_133.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 7.985]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_134.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 4.015]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_135.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 4.015]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_136.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 7.985]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_137.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 4.103]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_138.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 2.703]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_139.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 4.384]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_140.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 4.727]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_141.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <mesh geometry={nodes.Solid1_122.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
      <group position={[2.05, 2.102, 0]}>
        <group position={[0, -2.054, 0]}>
          <mesh geometry={nodes.Solid1_143.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, 0, 0]}>
          <mesh geometry={nodes.Solid1_144.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -2.054, 0]}>
          <mesh geometry={nodes.Solid1_145.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -2.006, 11.952]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_146.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 0.048]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_147.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 0.048]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_148.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 11.952]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_149.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, 0, 0.05]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_150.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 0.05]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_151.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 11.95]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_152.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.895, 0, 11.95]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_153.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 7.985]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_154.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.9, -0.048, 4.015]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Solid1_155.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 4.015]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_156.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0, -0.048, 7.985]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Solid1_157.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 5.077]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_158.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 5.723]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_159.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 6.178]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_160.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 6.822]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_161.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 7.277]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_162.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 7.923]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_163.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.805, -2.054, 5.083]}>
          <mesh geometry={nodes.Solid1_164.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.805, -2.054, 6.183]}>
          <mesh geometry={nodes.Solid1_165.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.805, -2.054, 7.283]}>
          <mesh geometry={nodes.Solid1_166.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.896, -2.054, 8.834]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_167.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 9.574]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_168.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 10.134]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_169.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.897, -2.054, 10.874]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_170.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.83, -2.054, 10.138]}>
          <mesh geometry={nodes.Solid1_171.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[0.83, -2.054, 8.839]}>
          <mesh geometry={nodes.Solid1_172.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.895, -2.054, 2.168]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_173.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <group position={[1.895, -2.054, 1.588]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Solid1_174.geometry} material={materials.SemiPolished} scale={0.01} />
        </group>
        <mesh geometry={nodes.Solid1_142.geometry} material={materials.SemiPolished} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/machine.glb')
